### ISSUE TITLE
Build failing?

### ISSUE THREAD

**Issue by dustMason** [aquavitae/docker-weasyprint#1]
Hi,

I'd love to use this for a project, but I can't seem get this to work after building locally. I can run your latest build using `docker run -p 5001:5001 aquavitae/weasyprint`, which lets me successfully convert html to PDFs (tested via curl).

However when I clone the repo and build it myself (`docker build . -t weasy && docker run -p 5001:5001 weasy`) the server boots and the health check URL works, but it errors out when using the same request that worked above.

```
[2016-10-15 04:41:54 +0000] [5] [INFO] Starting gunicorn 19.4.0
[2016-10-15 04:41:54 +0000] [5] [INFO] Listening at: http://0.0.0.0:5001 (5)
[2016-10-15 04:41:54 +0000] [5] [INFO] Using worker: sync
[2016-10-15 04:41:54 +0000] [8] [INFO] Booting worker with pid: 8
2016-10-15 04:42:05,008 INFO: POST  /pdf?filename=unnamed.pdf [in /usr/src/app/wsgi.py:50]
2016-10-15 04:42:05,027 ERROR: Exception on /pdf [POST] [in /usr/local/lib/python3.5/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/wsgi.py", line 51, in generate
    html = HTML(string=request.data)
  File "/usr/local/lib/python3.5/site-packages/weasyprint/__init__.py", line 92, in __init__
    namespaceHTMLElements=False)
  File "/usr/local/lib/python3.5/site-packages/html5lib/html5parser.py", line 35, in parse
    return p.parse(doc, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/html5lib/html5parser.py", line 235, in parse
    self._parse(stream, False, None, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/html5lib/html5parser.py", line 85, in _parse
    self.tokenizer = _tokenizer.HTMLTokenizer(stream, parser=self, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/html5lib/_tokenizer.py", line 36, in __init__
    self.stream = HTMLInputStream(stream, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/html5lib/_inputstream.py", line 151, in HTMLInputStream
    return HTMLBinaryInputStream(source, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

Has something changed upstream causing this to break? I tried modifying the Dockerfile to start from `python:3.5.0-onbuild` and `python:3.5.1-onbuild` with no luck. I don't have enough experience with Python to go further.

Maybe you can run the circle-ci build again to see if it's just my environment?

Thanks

**Comment by dustMason** [comment]
Nevermind. Fixed by upgrading to weasyprint 0.31. I found an issue that referenced this problem https://github.com/Kozea/WeasyPrint/issues/334
